script:
  - npm test
language: node_js
node_js:
  - "0.10"
before_install: npm install -g grunt-cli
install: npm install
before_script:
  - bower install
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - webdriver-manager update
  - sleep 3
